<a href="https://colab.research.google.com/github/aliyahaslam/FINAL-YEAR-PROJECT-/blob/main/Final_Year_Project_Cleaning_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
uk_economy = pd.read_csv('/content/GENERAL ECONOMY DATASET .csv')
uk_economy.head()

  DATE   INFLATION RATE  DATE  UNEMPLOYMENT RATE
0  2018             2.3  2018                 4.2
1  2019             1.7  2019                 3.9
2  2020             1.0  2020                 4.7
3  2021             2.5  2021                 4.6
4  2022             7.9  2022                 3.9

In [ ]:
uk_economy.shape

(102, 4)

In [ ]:
uk_economy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DATE                102 non-null    object
 1   INFLATION RATE      102 non-null    float64
 2   DATE                102 non-null    object
 3   UNEMPLOYMENT RATE   102 non-null    float64
dtypes: float64(2), object(2)
memory usage: 3.3+ KB

In [ ]:
uk_economy.describe()

       INFLATION RATE  UNEMPLOYMENT RATE
count      102.000000          102.000000
mean         3.712745            4.210784
std          2.858812            0.412648
min          0.500000            3.600000
25%          1.700000            3.900000
50%          2.300000            4.100000
75%          6.275000            4.300000
max          9.600000            5.300000

In [ ]:
uk_economy.isnull().sum()

DATE                  0
INFLATION RATE        0
DATE                  0
UNEMPLOYMENT RATE     0
dtype: int64

In [ ]:
usa_economy = pd.read_csv('/content/USA General Economy.csv')
usa_economy.head()

,Month,Year,Consumer Confidence Index TX,Consumer Confidence West South Central,Consumer Confidence Index US,PCE Deflator,Consumer Price Index TX,Consumer Price Index U.S.,CPI U.S. Ex Food and Energy,Nonfarm Employment TX,...,Retail Diesel Price TX,Nonfarm Employment Illinois,Nonfarm Employment Florida,Nonfarm Employment New York,Nonfarm Employment Texas,Nonfarm Employment California,Gross Value Crude Oil Production,Gross Value Natural Gas Production,Motor Fuel Taxed Gasoline,Motor Fuel Taxed Diesel
0,JANUARY,2018,151.0,142.3,124.3,NaN,225.954,247.867,NaN,12.358,...,2.813,6080.3,8678.2,9609.1,12356.1,17037.0,6911.65,2652.83,1156.9,388.8
1,FEBRUARY,2018,154.7,144.9,130.0,NaN,227.441,248.991,NaN,12.396,...,2.835,6092.0,8704.3,9638.8,12396.2,17084.8,6308.18,2508.84,1111.2,402.9
2,MARCH,2018,139.2,129.7,127.0,NaN,227.746,249.554,NaN,12.433,...,2.796,6110.0,8725.6,9652.8,12439.5,17093.0,7188.05,2450.64,1050.1,361.0
3,APRIL,2018,141.5,135.4,125.6,NaN,228.152,250.546,NaN,12.451,...,2.897,6086.5,8739.8,9657.4,12450.2,17108.8,7378.44,2466.27,1222.5,416.7
4,MAY,2018,147.3,141.1,128.8,NaN,230.043,251.588,NaN,12.486,...,3.019,6091.7,8753.6,9669.9,12487.1,17125.7,7854.88,2813.01,1176.4,404.1

In [ ]:
usa_economy.shape

(72, 31)

In [ ]:
usa_economy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 31 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Month                                   72 non-null     object
 1   Year                                    72 non-null     int64
 2   Consumer Confidence Index TX            72 non-null     float64
 3   Consumer Confidence West South Central  72 non-null     float64
 4   Consumer Confidence Index US            72 non-null     float64
 5   PCE Deflator                            0 non-null      float64
 6   Consumer Price Index TX                 72 non-null     float64
 7   Consumer Price Index U.S.               72 non-null     float64
 8   CPI U.S. Ex Food and Energy             0 non-null      float64
 9   Nonfarm Employment TX                   72 non-null     float64
 10  Nonfarm Employment U.S.                 72 non-null     float64
 11  Unemployment TX                         72 non-null     float64
 12  Unemployment U.S.                       72 non-null     float64
 13  Single Family Building Permits TX       72 non-null     int64
 14  Multi Family Building Permits TX        72 non-null     int64
 15  Existing Single Family Home Sales TX    72 non-null     int64
 16  Existing Single Family Home Price TX    72 non-null     int64
 17  Non Residential Building Construction   72 non-null     float64
 18  Total Sales Tax Collections Retail TX   72 non-null     float64
 19  Total Sales Tax Collections TX          72 non-null     float64
 20  Retail Gasoline Price TX                72 non-null     float64
 21  Retail Diesel Price TX                  72 non-null     float64
 22  Nonfarm Employment Illinois             72 non-null     float64
 23  Nonfarm Employment Florida              72 non-null     float64
 24  Nonfarm Employment New York             72 non-null     float64
 25  Nonfarm Employment Texas                72 non-null     float64
 26  Nonfarm Employment California           72 non-null     float64
 27  Gross Value Crude Oil Production        72 non-null     float64
 28  Gross Value Natural Gas Production      72 non-null     float64
 29  Motor Fuel Taxed Gasoline               72 non-null     float64
 30  Motor Fuel Taxed Diesel                 72 non-null     float64
dtypes: float64(25), int64(5), object(1)
memory usage: 17.6+ KB

In [ ]:
usa_economy.describe()

,Year,Consumer Confidence Index TX,Consumer Confidence West South Central,Consumer Confidence Index US,PCE Deflator,Consumer Price Index TX,Consumer Price Index U.S.,CPI U.S. Ex Food and Energy,Nonfarm Employment TX,Nonfarm Employment U.S.,...,Retail Diesel Price TX,Nonfarm Employment Illinois,Nonfarm Employment Florida,Nonfarm Employment New York,Nonfarm Employment Texas,Nonfarm Employment California,Gross Value Crude Oil Production,Gross Value Natural Gas Production,Motor Fuel Taxed Gasoline,Motor Fuel Taxed Diesel
count,72.00000,72.000000,72.000000,72.000000,0.0,72.000000,72.000000,0.0,72.000000,72.000000,...,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000,72.000000
mean,2020.50000,122.681944,116.334722,113.681944,NaN,247.805569,272.306944,NaN,12.950950,149.487597,...,3.289986,5976.690278,9043.654167,9416.706944,12949.379167,17142.297222,8664.379444,3625.647083,1163.993056,408.473611
std,1.71981,19.350513,18.260248,14.597360,NaN,18.663451,20.361095,NaN,0.611875,5.384958,...,0.843089,211.082958,471.639612,478.461266,613.398786,735.965750,2917.974110,1926.660457,86.602660,38.081566
min,2018.00000,86.900000,84.400000,85.700000,NaN,225.954000,247.867000,NaN,11.519000,130.513000,...,2.145000,5318.600000,7802.900000,7852.400000,11517.400000,14946.100000,1904.580000,1082.960000,788.400000,302.600000
25%,2019.00000,105.375000,100.975000,103.025000,NaN,233.381500,256.327500,NaN,12.538250,147.749000,...,2.796750,5885.875000,8736.250000,9239.300000,12524.525000,17017.700000,6926.192500,2364.370000,1127.900000,386.350000
50%,2020.50000,120.250000,111.850000,111.750000,NaN,236.131000,261.028000,NaN,12.845500,150.236000,...,3.009500,6091.200000,8993.350000,9655.100000,12843.650000,17360.100000,8130.810000,2930.650000,1182.900000,407.350000
75%,2022.00000,141.500000,135.025000,126.850000,NaN,268.880500,296.197250,NaN,13.444150,152.623000,...,3.819750,6114.350000,9430.150000,9737.350000,13444.150000,17689.175000,10775.632500,4709.415000,1222.525000,426.550000
max,2023.00000,154.700000,146.100000,137.900000,NaN,281.716000,307.789000,NaN,14.034500,157.304000,...,5.393000,6151.800000,9865.800000,9835.100000,14034.500000,17948.900000,15060.060000,9101.000000,1283.500000,531.500000

In [ ]:
usa_economy.isnull().sum()

Month                                      0
Year                                       0
Consumer Confidence Index TX               0
Consumer Confidence West South Central     0
Consumer Confidence Index US               0
PCE Deflator                              72
Consumer Price Index TX                    0
Consumer Price Index U.S.                  0
CPI U.S. Ex Food and Energy               72
Nonfarm Employment TX                      0
Nonfarm Employment U.S.                    0
Unemployment TX                            0
Unemployment U.S.                          0
Single Family Building Permits TX          0
Multi Family Building Permits TX           0
Existing Single Family Home Sales TX       0
Existing Single Family Home Price TX       0
Non Residential Building Construction      0
Total Sales Tax Collections Retail TX      0
Total Sales Tax Collections TX             0
Retail Gasoline Price TX                   0
Retail Diesel Price TX                     0
Nonfarm Employment Illinois                0
Nonfarm Employment Florida                 0
Nonfarm Employment New York                0
Nonfarm Employment Texas                   0
Nonfarm Employment California              0
Gross Value Crude Oil Production           0
Gross Value Natural Gas Production         0
Motor Fuel Taxed Gasoline                  0
Motor Fuel Taxed Diesel                    0
dtype: int64